-- --------------------------------------------------------
-- Servidor:                     127.0.0.1
-- Versão do servidor:           10.4.32-MariaDB - mariadb.org binary distribution
-- OS do Servidor:               Win64
-- HeidiSQL Versão:              12.8.0.6908
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Copiando estrutura do banco de dados para db_node
CREATE DATABASE IF NOT EXISTS `db_node` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci */;
USE `db_node`;

-- Copiando estrutura para tabela db_node.cadastro_usuario
CREATE TABLE IF NOT EXISTS `cadastro_usuario` (
  `id` int(111) NOT NULL AUTO_INCREMENT,
  `nome` varchar(100) NOT NULL DEFAULT '0',
  `email` varchar(100) NOT NULL DEFAULT '0',
  `senha` varchar(100) NOT NULL DEFAULT '0',
  `imagem_perfil` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=52 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Copiando dados para a tabela db_node.cadastro_usuario: ~2 rows (aproximadamente)
INSERT INTO `cadastro_usuario` (`id`, `nome`, `email`, `senha`, `imagem_perfil`) VALUES
	(50, 'vini', '123', 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3', NULL),
	(51, 'vini', 'vinicius@gmail.com', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 'foto-15.png');

-- Copiando estrutura para tabela db_node.favoritos
CREATE TABLE IF NOT EXISTS `favoritos` (
  `id_user` int(11) DEFAULT NULL,
  `id_peixe` int(11) DEFAULT NULL,
  KEY `FK_favoritos_cadastro_usuario` (`id_user`),
  KEY `FK_favoritos_peixes` (`id_peixe`),
  CONSTRAINT `FK_favoritos_cadastro_usuario` FOREIGN KEY (`id_user`) REFERENCES `cadastro_usuario` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_favoritos_peixes` FOREIGN KEY (`id_peixe`) REFERENCES `peixes` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- Copiando dados para a tabela db_node.favoritos: ~1 rows (aproximadamente)
INSERT INTO `favoritos` (`id_user`, `id_peixe`) VALUES
	(51, 2);

-- Copiando estrutura para tabela db_node.peixes
CREATE TABLE IF NOT EXISTS `peixes` (
  `id` int(111) NOT NULL AUTO_INCREMENT,
  `nome_peixe` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `desc_peixe` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `isca_pref` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `desc_isca` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `local_pesca` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `profundidade_min` float NOT NULL DEFAULT 0,
  `profundidade_max` float NOT NULL DEFAULT 0,
  `tecnica` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `img_peixe` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `peso_min` float NOT NULL DEFAULT 0,
  `peso_max` float NOT NULL DEFAULT 0,
  `tamanho_min` float NOT NULL DEFAULT 0,
  `tamanho_max` float NOT NULL DEFAULT 0,
  `epoca` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `horario` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  `anzol` varchar(200) CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=84 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_hungarian_ci;

-- Copiando dados para a tabela db_node.peixes: ~76 rows (aproximadamente)
INSERT INTO `peixes` (`id`, `nome_peixe`, `desc_peixe`, `isca_pref`, `desc_isca`, `local_pesca`, `profundidade_min`, `profundidade_max`, `tecnica`, `img_peixe`, `peso_min`, `peso_max`, `tamanho_min`, `tamanho_max`, `epoca`, `horario`, `anzol`) VALUES
	(1, 'Tucunaré', 'Peixe predador, forte, cores vibrantes', 'Iscas artificiais e vivas', 'Plugs, hélices, lambaris', 'Lagos, rios, represas', 0, 3, 'Arremesso e recolhimento', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTpjroq068YatH-zEPmQkMzkV6i0PIRYJL_A&s', 2, 5, 40, 60, 'Verão,', 'Manhã e Tarde', '2/0 3/0 4/0'),
	(2, 'Pirarucu', 'Um dos maiores peixes de água doce, escamas grandes', 'Peixes inteiros, carne', 'Pedaços de carne, peixes', 'Rios e lagos amazônicos', 0, 5, 'Espera com isca viva', 'https://agriconline.com.br/portal/wp-content/uploads/2023/01/pirarucu.jpg', 40, 100, 100, 300, 'Inverno,', 'Tarde e Noite', '10/0,11/0,12/0,'),
	(3, 'Pintado', 'Peixe de couro com corpo alongado, típico do Pantanal', 'Peixes inteiros, carne', 'Pedaços de peixe ou carne', 'Rios e lagos do Pantanal', 3, 10, 'Espera no fundo', 'https://leonardoconcon.com.br/wp-content/uploads/2022/09/peixe-pintado-pescador-johnny-hoffmann-rio.jpg', 10, 20, 80, 120, 'Verão,', 'Noite,Madrugada,', '8/0,9/0,10/0,'),
	(4, 'Traíra', 'Peixe agressivo com dentes afiados', 'Iscas artificiais e naturais', 'Soft baits, spinners, pequenos peixes, rãs', 'Lagos, lagoas e rios', 0, 2, 'Arremesso e recolhimento', 'https://i.pinimg.com/736x/5a/3b/5d/5a3b5db16c6a3132ce5a3261182d3aee.jpg', 1, 3, 40, 60, 'Inverno,Primavera,Verão,Outono,', 'Manhã,Tarde,', '2/0,3/0,4/0,'),
	(5, 'Tambaqui', 'Peixe robusto, corpo redondo, muito apreciado na pesca e culinária', 'Frutas, ração, milho', 'Iscas naturais como frutas e sementes', 'Rios e lagos na Amazônia', 0, 3, 'Espera com isca natural', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ6WpS9SEZ6ro2Y_Qt_fbkBdAygnD6rN0L0AGdQEVkAPqBFyizckUuyMg7SJyvJb3XRnww&usqp=CAU', 10, 30, 70, 90, 'Verão,', 'Manhã,Tarde,', '4/0,5/0,6/0,'),
	(6, 'Matrinxã', 'Peixe rápido e esportivo, com corpo alongado e escamas prateadas', 'Frutas, ração, milho', 'Frutas como banana e goiaba, milho verde', 'Frutas como banana e goiaba, milho verde', 0, 2, 'Arremesso e corrico', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQc891BSAv1OaSI9EayS4vEtew69LIxUH6Y4g&s', 2, 5, 50, 70, 'Inverno,Primavera,Verão,Outono,', 'Manhã cedo', '2/0,3/0,4/0,'),
	(7, 'Piau', 'Peixe de escamas, comum em rios com correnteza leve', 'Minhoca, milho, ração', 'Iscas naturais como minhocas e milho', 'Rios e córregos', 1, 4, 'Pesca de fundo com boia', 'https://i0.wp.com/zootecniabrasil.com/wp-content/uploads/2023/04/piau-tres-pintas.jpg?fit=1200%2C800&ssl=1', 1, 3, 30, 50, 'Verão,', 'Manhã e Tarde', '1/0,2/0,3/0,'),
	(8, 'Lambari', 'Peixe pequeno, muito utilizado como isca viva', 'Massa, pedaços de pão, minhocas', 'Massa preparada, pedaços de pão', 'Lagos, rios e córregos', 0, 1, 'Pesca de espera com boia', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSX8dpk8BDVdZ8GiREcuQWHLt_hglCKPI87LQ&s', 0.1, 0.5, 5, 10, 'Inverno,Primavera,Verão,Outono,', 'Qualquer horário', '17,16,15,'),
	(9, 'Corvina', 'Peixe de escamas, predador, encontrado em águas mais profundas', 'Sardinha, peixes pequenos, iscas artificiais', 'Sardinha, pequenos peixes vivos', 'Lagos, represas e rios profundos', 5, 20, 'Pesca de fundo ou corrico', 'https://i.pinimg.com/originals/62/01/4c/62014c4eda52dc342b158596faa64cb5.jpg', 1, 5, 40, 60, 'Inverno,Primavera,Verão,Outono,', 'Noite,Madrugada,', '3/0,4/0,5/0,'),
	(10, 'Pacu', 'Peixe de escamas, corpo alto e comprimido, muito comum em rios', 'Frutas, milho, ração', 'Iscas naturais como frutas e grãos', 'Rios e lagos na Bacia Amazônica', 1, 3, 'Pesca de espera ou corrico', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ5a9oUEDZNSiFJyxQ1IWp-GYXeVvH8v0Xeww&s', 3, 10, 40, 60, 'Verão,', 'Manhã,Tarde,', '3/0,4/0,5/0,'),
	(11, 'Pirapitinga', 'Similar ao pacu, com corpo robusto e hábitos herbívoros', 'Frutas, ração, milho', 'Frutas e grãos, iscas naturais', 'Rios e lagos da Amazônia', 1, 5, 'Pesca de espera', 'https://s2.glbimg.com/vM1_GJY68rKIX5OpT744VGpumzM=/e.glbimg.com/og/ed/f/original/2018/05/30/fxw055.jpg', 5, 15, 80, 100, 'Verão,', 'Manhã,Tarde,', '4/0,5/0,6/0,'),
	(12, 'Jaú', 'Peixe de couro, grande, corpo robusto, apreciado na pesca esportiva', 'Peixes inteiros, carne', 'Pedaços de carne ou peixe, minhocas grandes', 'Rios profundos da Amazônia', 10, 30, 'Pesca de fundo com boia', 'https://i.ytimg.com/vi/cXDw5DGaAp0/sddefault.jpg', 20, 50, 100, 150, 'Verão,', 'Noite,Madrugada,', '8/0,9/0,10/0,11/0,12/0,'),
	(13, 'Aruanã', 'Peixe ágil, salta fora da água, predador, comum em rios e lagos', 'Insetos, pequenos peixes, iscas artificiais', 'Insetos, peixes vivos ou mortos, rãs', 'Rios e lagos da Amazônia', 0, 2, 'Arremesso e recolhimento', 'https://pescanapraia.com/wp-content/uploads/2015/10/aruana-930x530_c.jpg', 2, 5, 60, 100, 'Verão,', 'Manhã,Tarde,', '3/0,4/0,5/0,'),
	(14, 'Curimatá', 'Peixe de escamas, pequeno a médio porte, encontrado em águas lentas', 'Massas, milho, minhocas', 'Massa preparada, milho verde, minhocas', 'Rios e lagos de correnteza lenta', 1, 3, 'Pesca de fundo', 'https://www.grupoaguasclaras.com.br/wp-content/uploads/2013/07/psj-curimbata-000-600x230-350x134.jpg', 0.5, 2, 20, 40, 'Inverno,Primavera,Verão,Outono,', 'Manhã e Tarde', '1/0,2/0,3/0,'),
	(15, 'Piranha', 'Peixe predador, agressivo, dentes afiados', 'Carne, peixes pequenos', 'Pedaços de carne ou peixe', 'Rios e lagos da Amazônia', 0, 2, 'Pesca de espera', 'https://t1.ea.ltmcdn.com/pt/posts/4/8/9/a_piranha_como_animal_de_estimacao_984_600.jpg', 0.5, 1, 15, 30, 'Inverno,Primavera,Verão,Outono,', 'Manhã e Tarde', '1/0,2/0,3/0,'),
	(16, 'Piau-Verdadeiro', 'Peixe de escamas, corpo alongado, presente em rios e lagos', 'Minhocas, massa, milho', 'Minhocas, massa preparada, milho verde', 'Rios e lagos de águas calmas', 1, 3, 'Pesca de fundo', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLp5sUMKcOkCgBVu0juCX-0DIdnLBWXEih1A&s', 1, 2, 30, 50, 'Verão,', 'Manhã e Tarde', '1/0,2/0,3/0'),
	(17, 'Jundiá', 'Peixe de couro, corpo alongado, comum em rios e lagos', 'Minhocas, peixes pequenos', 'Minhocas grandes, pequenos peixes vivos', 'Rios e lagos de águas escuras', 2, 5, 'Pesca de fundo', 'https://i.pinimg.com/originals/0d/4f/ae/0d4faed2d633decf4b0b027a4a2b5565.jpg', 2, 4, 40, 60, 'Inverno,Primavera,Verão,Outono,', 'Noite,Madrugada,', '4/0,5/0,6/0,'),
	(18, 'Pirarara', 'Peixe de couro, grande, com barbatanas vermelhas', 'Peixes inteiros, carne', 'Pedaços de carne ou peixe', 'Rios e lagos amazônicos', 5, 20, 'Pesca de fundo', 'https://blog.pescagerais.com.br/wp-content/uploads/2020/10/peixe-pirarara-rio-na-amazonia-pescador-otavio-vieira.jpg', 20, 50, 100, 150, 'Verão,', 'Noite,Madrugada,', '8/0,9/0,10/0,11/0,12/0,'),
	(19, 'Trairão', 'Peixe agressivo, semelhante à traíra, maior e mais robusto', 'Peixes pequenos, rãs, iscas artificiais', 'Peixes vivos, rãs, plugs', 'Lagos, lagoas, rios', 1, 3, 'Arremesso e recolhimento', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRCclGQiQAdAFWy2hajhr78uze1FUeRG5ivgg&s', 5, 10, 70, 100, 'Inverno,Primavera,Verão,Outono,', 'Manhã,Tarde,', '4/0,5/0,6/0,'),
	(20, 'Bicuda', 'Peixe predador, corpo alongado, muito ágil', 'Peixes pequenos, iscas artificiais', 'Peixes pequenos, iscas artificiais', 'Rios de águas rápidas', 0, 2, 'Arremesso e recolhimento', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRYqaQCze4f2gnW-7Jw_qxAAqkUZh9c3LKG5Q&s', 2, 4, 60, 80, 'Verão,', 'Manhã,Tarde,', '3/0,4/0,5/0,'),
	(21, 'Apapá', 'Peixe de escamas, corpo prateado, muito ágil', 'Frutas, plugs, hélices', 'Frutas, plugs, hélices', 'Rios e lagos amazônicos', 0, 2, 'Arremesso e recolhimento', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ11j_4ijmkmMiX3RAc2KYSZibWyu1jrPx7Yg&s', 1, 3, 50, 70, 'Verão,', 'Manhã,Tarde,', '3/0,4/0,5/0,'),
	(22, 'Bagre', 'Peixe de couro, pequeno a médio porte, encontrado em rios e lagos', 'Minhocas, peixes pequenos', 'Minhocas, pedaços de peixe', 'Rios e lagos de águas escuras', 1, 3, 'Pesca de fundo', 'https://pescanapraia.com/wp-content/uploads/2011/11/bagre1-930x530_c.jpg', 1, 3, 40, 60, 'Inverno,Primavera,Verão,Outono,', 'Noite e Madrugada', '2/0,3/0,4/0,'),
	(23, 'Surubim', 'Peixe de couro, corpo alongado, comum em rios grandes', 'Peixes inteiros, carne', 'Pedaços de carne ou peixe, minhocas grandes', 'Rios e lagos amazônicos', 5, 20, 'Pesca de fundo', 'https://www.cobraspesca.com/wp-content/uploads/2017/06/Peixe-Surubim1.jpg', 10, 30, 100, 150, 'Verão,', 'Noite,Madrugada,', '8/0,9/0,10/0,'),
	(24, 'Cará', 'Peixe pequeno a médio, comum em rios e lagos, de fácil captura', 'Minhocas, ração, pequenos insetos', 'Minhocas, ração, larvas', 'Rios e lagos amazônicos', 5, 20, 'Pesca de fundo', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR7BlOcAuyvlkNOToEMEcbPK08fb_1vEW60EA&s', 10, 30, 100, 150, 'Verão,', 'Noite,Madrugada,', '8/0,9/0,10/0,'),
	(25, 'Piauçu', 'Peixe de escamas, grande, robusto, comum em rios e lagos', 'Minhocas, milho, massa', 'Minhocas, massa preparada, milho verde', 'Rios e lagos de águas calmas', 1, 3, 'Pesca de fundo', 'https://files.agro20.com.br/uploads/2020/09/Piau%C3%A7u-2.jpg', 2, 5, 50, 70, 'Verão,', 'Manhã e Tarde', '2/0,3/0,4/0,'),
	(26, 'Lambari-do-rabo-vermelho', 'Peixe pequeno, com rabo vermelho, muito ativo', 'Massa, larvas, minhocas', 'Massa preparada, minhocas pequenas', 'Lagos, rios e córregos', 0, 1, 'Pesca de espera com boia', 'https://i.pinimg.com/736x/e3/53/cd/e353cdf6d17349838a61c4470a9f6f54.jpg', 0.02, 0.05, 5, 10, 'Inverno,Primavera,Verão,Outono,', 'Qualquer horário', '16,15,14,'),
	(27, 'Sardinha-de-água-doce', 'Peixe pequeno, prateado, encontrado em grandes cardumes', 'Massa, larvas, pedaços de pão', 'Massa preparada, pedaços de pão', 'Lagos, rios e represas', 0, 2, 'Pesca de espera com boia', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTLca6R9Yxsb3_E2pQTXlofejLL1K1b2T4u_g&s', 0.02, 0.05, 10, 20, 'Inverno,Primavera,Verão,Outono,', 'Manhã e Tarde', '16,15,14,'),
	(28, 'Tilápia', 'Peixe de escamas, resistente, muito comum em lagos e represas', 'Ração, milho, minhocas', 'Ração de peixe, milho verde, minhocas', 'Lagos, represas, rios', 1, 3, 'Pesca de espera ou corrico', 'https://i0.wp.com/zootecniabrasil.com/wp-content/uploads/2023/05/tilapia-do-nilo-comum.jpg?fit=1536%2C1097&ssl=1', 1, 3, 20, 40, 'Inverno,Primavera,Verão,Outono,', 'Manhã e Tarde', '2/0,3/0,4/0,'),
	(29, 'Dourado-Amarelo', 'Peixe grande, predador, muito esportivo, típico de rios rápidos', 'Peixes pequenos, iscas artificiais', 'Peixes vivos, plugs, spinners', 'Rios de águas rápidas', 1, 3, 'Corrico e arremesso', 'https://s3-sa-east-1.amazonaws.com/loja2/f95bc70f8bcf9bbd01263c73879b44ea.jpg', 5, 10, 70, 100, 'Verão,', 'Manhã,Tarde,', '5/0,6/0,7/0,8/0,'),
	(30, 'Curimbatá', 'Peixe de escamas, corpo alongado, presente em rios e lagos', 'Minhocas, ração, milho', 'Minhocas, ração de peixe, milho verde', 'Rios e lagos de águas calmas', 1, 3, 'Pesca de fundo', 'https://pescanapraia.com/wp-content/uploads/2015/10/curimba-930x530_c.jpg', 2, 4, 30, 60, 'Verão,', 'Manhã e Tarde', '1/0,2/0,3/0,'),
	(31, 'Mandubé', 'Peixe de couro, pequeno a médio, muito apreciado na pesca esportiva', 'Minhocas, peixes pequenos', 'Minhocas grandes, pequenos peixes vivos', 'Rios e lagos de águas escuras', 2, 5, 'Pesca de fundo', 'https://blogdopescador.com/wp-content/uploads/2021/11/mandube-onde-encontrar.jpg', 1, 2, 30, 50, 'Inverno,Primavera,Verão,Outono,', 'Noite,Madrugada,', '4/0,5/0,6/0,'),
	(33, 'Jaraqui', 'Peixe de escamas, corpo comprimido, comum na Bacia Amazônica', 'Frutas, ração, milho', 'Frutas como goiaba e milho verde', 'Rios e lagos da Amazônia', 0, 2, 'Pesca de espera ou corrico', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTEto5RTADmKEj7CN_RYzErV3l5-501qysjhw&s', 0.5, 2, 10, 25, 'Verão,', 'Manhã e Tarde', '2/0,3/0,4/0,'),
	(34, 'Surubim-chicote', 'Peixe de couro, corpo alongado, típico da Bacia do São Francisco', 'Peixes inteiros, carne', 'Pedaços de carne ou peixe, minhocas grandes', 'Rios e lagos de águas profundas', 5, 15, 'Pesca de fundo', 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEg82JmLUhOPY_Kiyw7jTk1J0ZAdrrH2qFXASsxmKf_QN5QIniHrOG4DlX_TM_CeSL2FBE2MlEZjn2Ve7TJZTA4Kq88btDOjSnFAY9jzC1nCuwr6qqivX_wmMzw1VcC3AZUwngCOWLsdc_Ph/s1600/lima+2.jpg', 10, 20, 100, 150, 'Verão,', 'Noite,Madrugada,', '8/0,9/0,10/0,11/0,12/0,'),
	(35, 'Apapá-do-norte', 'Peixe de escamas, corpo alongado, muito ativo, comum na Amazônia', 'Insetos, frutas, iscas artificiais', 'Insetos, plugs, hélices', 'Rios e lagos da Amazônia', 0, 2, 'Arremesso e recolhimento', 'https://static.wixstatic.com/media/03b554_cd543454caa546f89fa6d846eefec33b.jpg/v1/fill/w_980,h_577,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/03b554_cd543454caa546f89fa6d846eefec33b.jpg', 1, 3, 500, 70, 'Verão,', 'Manhã,Tarde,', '3/0,4/0,5/0,'),
	(36, 'Piranambu', 'Peixe de couro, corpo robusto, comum em águas profundas', 'Peixes inteiros, carne', 'Pedaços de carne ou peixe, minhocas grandes', 'Rios e lagos da Amazônia', 10, 30, 'Pesca de fundo', 'https://pescanapraia.com/wp-content/uploads/2015/06/barbado.jpg', 20, 50, 100, 150, 'Verão,', 'Noite,Madrugada,', '8/0,9/0,10/0,11/0,12/0,'),
	(37, 'Piau-três-pintas', 'Peixe de escamas, pequeno a médio porte, encontrado em rios', 'Minhocas, milho, ração', 'Minhocas, milho verde, ração de peixe', 'Rios de correnteza moderada', 1, 3, 'Pesca de fundo', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRtlbMoLkMIVJDY0m8725OeRU__uE7k6jHUDA&s', 1, 2, 30, 50, 'Inverno,Primavera,Verão,Outono,', 'Manhã e Tarde', '1/0,2/0,3/0,'),
	(38, 'Peixe-Cachorra', 'Peixe predador, com dentes afiados, muito agressivo', 'Peixes pequenos, iscas artificiais', 'Peixes vivos, plugs, spinners', 'Rios de águas rápidas', 0, 2, 'Arremesso e recolhimento', 'https://i.ytimg.com/vi/sdZanxdHhHY/maxresdefault.jpg', 2, 4, 50, 70, 'Verão,', 'Manhã,Tarde,', '8/0,9/0,10/0,'),
	(39, 'Jacundá', 'Peixe pequeno, corpo alongado e escamas duras', 'Minhoca', 'Isca natural, minhoca viva', 'Riachos, lagoas e margens de rios', 0.5, 1, 'Arremesso leve', 'https://files.agro20.com.br/uploads/2019/04/jacund%C3%A1.png', 0.05, 0.2, 10, 20, 'Inverno,Primavera,Verão,Outono,', 'Manhã', '10/0,11/0,12/0,'),
	(40, 'Sardinha-guaçu', 'Peixe pequeno e prateado, de hábitos coletivos', 'Massa de farinha', 'Isca caseira, feita de farinha e água', 'Rios e lagos', 0.5, 2, 'Pesca de espera', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXh499pEJ3ew6oakoTVwikr64jqCX3VAkDif3IuFMHqmee3IUAg2dent5Azh6SiwamUtE&usqp=CAU', 0.1, 0.5, 15, 30, 'Verão,', 'Verão,', '8/0,9/0,10/0,'),
	(41, 'Cará-cascudo', 'Peixe de corpo achatado e couro áspero', 'Peixe pequeno', 'Isca natural, pedaços de peixes menores', 'Lagoas, represas e margens de rios', 0.5, 1, 'Arremesso', 'https://images.tcdn.com.br/img/img_prod/749804/cascudo_cara_chata_l259_1157_1_a273a91847c4770b4f792cbaddc2294e.jpg', 0.2, 0.5, 15, 25, 'Primavera,', 'Tarde,', '6,7,8,'),
	(43, 'Lambari-de-rabo-amarelo', 'Peixe pequeno, corpo prateado e cauda amarela', 'Massa de pão', 'Isca caseira, feita de pedaços de pão', 'Rios, riachos e lagoas', 0.3, 1, 'Pesca de espera', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTuT1Mr8WOxuFrP9azQD6uD5wgC86tSeZcItA&s', 10, 20, 5, 10, 'Inverno,Primavera,Verão,Outono,', 'Manhã cedo', '18,19,20,'),
	(44, 'Piracanjuba', 'Peixe de corpo alongado, com escamas prateadas', 'Frutas', 'Isca natural, frutas como goiaba ou pitanga', 'Rios de correnteza', 1, 3, 'Corrico', 'https://s2.glbimg.com/9zqdMc3hIvREoty1HyQ3nf365To=/s.glbimg.com/jo/g1/f/original/2015/02/04/sidneymartins.jpg', 1, 5, 40, 70, 'Outono,', 'Manhã,', '3/0,4/0,5/0,'),
	(45, 'Piranha-preta', 'Peixe de corpo robusto, com dentes afiados e coloração escura', 'Peixe ou carne', 'Isca natural, pedaços de carne ou peixes', 'Rios e lagos', 1, 3, 'Arremesso', 'https://blogdopescador.com/wp-content/uploads/2021/11/piranha-preta..jpg', 0.5, 2, 20, 40, 'Verão,', 'Tarde', '2/0,3/0,4/0,'),
	(46, 'Barbado', 'Peixe de couro, com longas barbilhas e corpo robusto', 'Minhoca', 'Isca natural, minhoca viva', 'Rios profundos', 3, 10, 'Pesca de fundo', 'https://lh3.googleusercontent.com/Jfdb7btisEjEinhKSs3krniw3XV5Cr6qaFAfxcJqUeiqaO9VrKZCET2bcalZ3eryj129cn24PLOZPKvkgZn3ahErp-lkNn2dnKIOE2iTKoPvyUTq0LeHbsvxCQuf729NwKjjLHM', 2, 8, 50, 80, 'Inverno,', 'Noite,', '4/0,5/0,6/0,'),
	(47, 'Jurupoca', 'Peixe de corpo alongado, coloração acinzentada', 'Peixe pequeno', 'Isca natural, peixes menores', 'Rios e lagos', 5, 5, 'Pesca de espera', 'https://www.aquarismopaulista.com/wp-content/uploads/2017/08/Hemisorubim-platyrhynchos4.jpg', 0.5, 2, 30, 60, 'Outono,', 'Amanhecer', '2/0,3/0,4/0,'),
	(48, 'Mandi', 'Peixe de couro, corpo achatado e pequeno porte', 'Minhoca ou massa', 'Isca natural, minhoca ou massa de pão', 'Rios e represas', 1, 3, 'Pesca de fundo', 'https://i.pinimg.com/736x/39/cf/2e/39cf2eb6aa0317fbf881c3c23be1b751.jpg', 0.3, 0.8, 20, 35, 'Inverno,Primavera,Verão,Outono,', 'Noite', '10,11,12,13,14,'),
	(49, 'Apaiari', 'Peixe de corpo robusto, com nadadeiras espinhosas', 'Grilo ou insetos', 'Isca natural, insetos vivos como grilos', 'Lagos, represas e margens de rios', 0.5, 2, 'Arremesso leve', 'https://http2.mlstatic.com/D_917469-MLB50567173301_072022-C.jpg', 0.2, 0.5, 15, 25, 'Primavera,', 'Tarde,', '6,7,8,'),
	(50, 'Acari', 'Peixe de couro, com corpo achatado e boca em forma de ventosa', 'Algas e vegetais aquáticos', 'Isca natural, pedaços de algas ou vegetais', 'Riachos, lagos e represas', 0.5, 3, 'Pesca de fundo', 'https://www.aquarismopaulista.com/wp-content/uploads/2014/08/Pterygoplichthys-pardalis1.jpg', 0.2, 0.5, 15, 25, 'Inverno,Primavera,Verão,Outono,', 'Manhã,', '8,9,10,'),
	(51, 'Cachara', 'Peixe de couro, corpo alongado com listras, típico do Pantanal', 'Peixes inteiros, carne', 'Pedaços de carne ou peixe, minhocas grandes', 'Rios e lagos do Pantanal', 5, 15, 'Pesca de fundo', 'https://files.agro20.com.br/uploads/2020/09/Cachara-1.jpg', 10, 20, 80, 120, 'Verão,', 'Noite,Madrugada,', '6/0,7/0,8/0,'),
	(52, 'Camorim', 'Peixe de corpo alongado, conhecido como robalo em algumas regiões', 'Camarão vivo', 'Isca natural, camarão ou crustáceos vivos', 'Manguezais, estuários e costa marítima', 0.5, 5, 'Corrico, arremesso', 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/46/Centropomus_parallelus_2.jpg/420px-Centropomus_parallelus_2.jpg', 1, 5, 30, 80, 'Primavera,', 'Manhã,', '2/0,3/0,4/0,5/0,'),
	(53, 'Pacu-caranha', 'Pacu-caranha	Peixe de corpo arredondado e escamas grossas', 'Frutas e grãos', 'Isca natural, frutas como goiaba ou milho', 'Rios, represas e lagos', 1, 3, 'Pesca de espera', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKhYeIV4Urnm8w9TFyvEX-zp8_xkumOzoQVw&s', 2, 10, 40, 70, 'Verão,', 'Manhã,', '3/0,4/0,5/0,6/0,'),
	(54, 'Sucuriú', 'Peixe de couro, corpo cilíndrico e nadadeiras fortes', 'Minhoca', 'Isca natural, minhoca viva', 'Rios de correnteza', 1, 6, 'Pesca de fundo', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTxSRGXEfX7nJqFeQ8PXrivwIOlzO1vGZ_YA&s', 0.5, 3, 30, 60, 'Inverno,Primavera,Verão,Outono,', 'Tarde', '2/0,3/0,4/0,'),
	(56, 'Cangati', 'Peixe de couro, corpo alongado e barbilhas longas', 'Peixe pequeno', 'Isca natural, peixes menores', 'Rios e lagos', 3, 10, 'Pesca de fundo', 'https://www.biofaces.com/img/c/1200/630/post/2019/06/1561232173.jpg', 1, 4, 40, 70, 'Inverno,', 'Noite,', '4/0,5/0,6/0,'),
	(57, 'Piau-Fumo', 'Peixe de escamas, corpo alongado e coloração escura', 'Minhocas, larvas, pequenos pedaços de frutas', 'Isca caseira, feita de farinha e água', 'Rios e riachos', 1, 3, 'Pesca de espera', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvLzDPkfWdLwL8kMVqVtfC27H_WwUhdErAtA&s', 0.3, 0.8, 20, 30, 'Outono,', 'Manhã cedo', '10,11,12,'),
	(58, 'Dourado', 'Conhecido como rei do rio, peixe forte e saltador', 'Iscas artificiais e naturais', 'Plugs, colheres, peixes pequenos', 'Rios de águas rápidas', 1, 3, 'Corrico e arremesso', 'https://i.pinimg.com/736x/64/9b/99/649b99fc2a7a6f76f5aa12a93a9568ca.jpg', 5, 10, 70, 100, 'Verão,', 'Manhã,Tarde,', '5/0,6/0,7/0,8/0,'),
	(59, 'Piraíba', 'Grande peixe de couro, corpo robusto e barbilhas longas', 'Peixe vivo', 'Isca natural, peixes vivos como tuviras', 'Rios profundos e corredeiras', 10, 30, 'Corrico, pesca de fundo', 'https://gazetadasemana.com.br/images/noticias/109093/31033428_peixe-pira.jpg.jpg', 50, 150, 150, 300, 'Inverno,Primavera,Verão,Outono,', 'Noite,', '8/0,9/0,10/0,11/0,12/0,'),
	(60, 'Piraputanga', 'Peixe de escamas, corpo alongado e coloração avermelhada', 'Frutas e insetos', 'Isca natural, frutas como pitanga ou insetos vivos', 'Rios e lagoas', 0.5, 2, 'Arremesso', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZ2hH-iy2vEhqS_-r5sfjl5c3sQQQyMt40Tn-5nhH1Af9VFo1ednRqOiM5E6OBYXAbuN8&usqp=CAU', 1, 3, 30, 50, 'Primavera,', 'Tarde', '2/0,3/0,4/0,'),
	(61, 'Pincachara', 'Peixe híbrido, corpo alongado e barbilhas', 'Peixe ou pedaços de carne', 'Isca natural, pedaços de peixe ou carne', 'Rios e lagos', 2, 5, 'Pesca de fundo', 'https://i0.wp.com/zootecniabrasil.com/wp-content/uploads/2021/01/surubins-1.jpg?fit=637%2C425&ssl=1', 5, 15, 70, 100, 'Inverno,', 'Noite,', '6/0,7/0,8/0,'),
	(63, 'Cachapira', 'Peixe híbrido entre cachara e piraíba, corpo robusto e alongado', 'Peixe vivo', 'Isca natural, peixes menores', 'Rios e represas', 2, 5, 'Pesca de fundo', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQBjZMLDi37jIAmNz3icLaPHExXoWKWDzv7WqLx607JJcVdcsjE9HFft2in4meS9QL7h2c&usqp=CAU', 10, 20, 60, 100, 'Inverno,', 'Noite,', '6/0,7/0,8/0,'),
	(64, 'Bagre-bandeira', 'Peixe Peixe de couro, com longas barbilhas e nadadeiras amplasescamas, corpo achatado e coloração variada', 'Minhoca ou pedaços de peixe', 'Isca natural, minhoca ou pedaços de peixe', 'Rios de fundo lamacento', 2, 6, 'Pesca de fundo', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTvxCDOyo_CrbPS3klX-BQKDIXNYw_azH1KsZM8Fncrny2Qe24Ws6VaCWKGq9XCfWXqQ1I&usqp=CAU', 1, 3, 30, 60, 'Inverno,Primavera,Verão,Outono,', 'Noite,', '4/0,5/0,6/0,'),
	(65, 'Corimbatá', 'Peixe de escamas, corpo alongado e coloração prateada', 'Massa de farinha', 'Isca caseira, feita de farinha e água', 'Rios e riachos', 0.5, 3, 'Pesca de espera', 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcQdNTrfYj0UvYGqK7cxDW0Ux_O54VAZ2355mUH9pSw00yxy9tqV', 0.3, 0.8, 20, 35, 'Outono,', 'Manhã', '10,11,12,'),
	(66, 'Tucunaré-Azul', 'Peixe de escama, corpo robusto e coloração azulada', 'Iscas artificiais', 'Iscas artificiais como plugs e spinners', 'Lagos, represas e rios', 1, 4, 'Arremesso e recolhimento', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT6hE8QZtNLcmXbz0WKkKLr1R85x-W3BslixCMz6z7uBf7krHsBpHJSOhKSilVO0BzqNzM&usqp=CAU', 2, 5, 30, 60, 'Verão,', 'Manhã,', '3/0,4/0,5/0,'),
	(67, 'Robalo', 'Peixe de corpo alongado, muito apreciado por sua carne', 'Camarão vivo', 'Isca natural, camarão ou crustáceos vivos', 'Manguezais, estuários e costa marítima', 0.5, 5, 'Corrico, arremesso', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTfcKliEDlFi8e12TKT-HlSpl2ayHQ5PZjuLj8JsXBaR6YwtDJyUvfza9s7193OG8rZxTA&usqp=CAU', 1, 5, 30, 80, 'Primavera,', 'Manhã,', '2/0,3/0,4/0,5/0,'),
	(68, 'Tambacu', 'Peixe híbrido entre tambaqui e pacu, corpo robusto', 'Frutas e grãos', 'Isca natural, frutas como goiaba ou milho', 'Lagos, represas e rios', 1, 3, 'Pesca de espera', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTJ3-hZMualofXXF7PpuvED0Foinmgiom6wA&s', 5, 20, 40, 90, 'Verão,', 'Manhã,', '4/0,5/0,6/0,'),
	(70, 'Carapeba', 'Peixe de escamas, corpo achatado e coloração prateada', 'Camarão vivo', 'Isca natural, camarão vivo', 'Manguezais, estuários e costa marítima', 0.5, 2, 'Arremesso', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbFwmUDzvTvPsSFlasOhkzA2aCU6EW_5yvtA&s', 0.2, 0.5, 15, 25, 'Primavera,', 'Tarde,', '8,9,10,'),
	(71, 'Mapará', 'Peixe de couro, corpo alongado e nadadeiras curtas', 'Peixe pequeno ou carne', 'Isca natural, pedaços de peixe ou carne', 'Rios e lagos', 1, 3, 'Pesca de fundo', 'https://www.aquarismopaulista.com/wp-content/uploads/2017/08/Hypophthalmus-edentatus.jpg', 1, 3, 30, 60, 'Inverno,Primavera,Verão,Outono,', 'Noite,', '4/0,5/0,6/0,'),
	(72, 'Jeju', 'Peixe de couro, corpo alongado e barbilhas curtas', 'Minhoca ou pequenos crustáceos', 'Isca natural, minhoca viva ou camarões pequenos', 'Rios e riachos', 1, 3, 'Pesca de fundo', 'https://www.aquarismopaulista.com/wp-content/uploads/2015/06/jeju04.jpg', 0.3, 0.8, 20, 35, 'Inverno,Primavera,Verão,Outono,', 'Tarde,', '8,9,10,'),
	(73, 'Três-Pintas', 'Peixe de escamas, com manchas características no corpo', 'Larvas de insetos', 'Isca natural, larvas de insetos aquáticos', 'Riachos e pequenos rios', 0.5, 2, 'Arremesso leve', 'https://media-cdn.tripadvisor.com/media/photo-m/1280/19/df/c9/dd/piraputanga.jpg', 0.2, 0.5, 15, 25, 'Primavera,', 'Manhã cedo', '10,11,12,'),
	(74, 'Cambucu', 'Peixe de escamas, corpo robusto e coloração escura', 'Camarão ou peixes pequenos', 'Isca natural, camarões vivos ou peixes menores', 'Costas rochosas e estuários', 1, 5, 'Corrico, arremesso', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUg3NKhuwzfA8cGov_Q8eKmo6TcyJcJUZ0KPFA5yGbXqQBdDXndGVOiDc4QZ7J8lgxY5I&usqp=CAU', 3, 7, 40, 70, 'Verão,', 'Manhã,', '3/0,4/0,5/0,'),
	(75, 'Piramutaba', 'Peixe de couro, corpo alongado e coloração acinzentada', 'Peixe vivo ou carne', 'Isca natural, peixes vivos ou pedaços de carne', 'Rios grandes e profundos', 5, 15, 'Pesca de fundo', 'https://lh6.googleusercontent.com/ibBs2zb3cPdU770APuD-pKCdpmLweZZUAeIdi7rS8lQSH14MUjM8TcSA07LOzPBtQDITqlqFIf-Sd_vxTAL8oWNeQX7Nerayw3LiYqYn-OxO1Hwxr-hdx52C9-q7-mYiYVlqzZg', 5, 15, 60, 150, 'Inverno,', 'Noite,', '6/0,7/0,8/0,9/0,10/0,'),
	(77, 'Peixe-Rei', 'Peixe de escamas, corpo alongado e coloração prateada', 'Iscas artificiais', 'Iscas artificiais pequenas como plugs ou jigs', 'Estuários, lagoas e rios', 0.5, 2, 'Arremesso leve', 'https://media.istockphoto.com/id/1403932326/pt/foto/flathead-silverside-fish-body-style-photograph-taken-on-the-rocky-background.jpg?s=612x612&w=0&k=20&c=ClvgId4W0CngfPrPWJ5IkaFcq8IRrfcc9S7ZuGnqY74=', 0.1, 0.3, 15, 25, 'Verão,', 'Tarde,', '8,9,10,'),
	(78, 'Dourado-Cachorro', 'Peixe de escamas, corpo alongado e coloração dourada com mandíbulas fortes', 'Peixes pequenos', 'Isca natural, peixes menores como lambaris', 'Rios de correnteza', 1, 5, 'Arremesso', 'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcROuviD8v17pffo7o_g55bygQhOJNZ9jPZ_JX2_J5xMRnBtnglD', 1, 5, 30, 70, 'Primavera,', 'Manhã,', '4/0,5/0,6/0,'),
	(79, 'Piabanha', 'Peixe de escamas, corpo alongado e coloração prateada', 'Massa de farinha', 'Isca caseira, feita de farinha e água', 'Rios e riachos', 0.5, 3, 'Pesca de espera', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSzEOgY5HzMORCYREUWCKrgYWD31MNujuo70p2PZ_j0Z_9P6gPUYC8bRXjfC7W0Zs81JqU&usqp=CAU', 0.2, 0.8, 20, 35, 'Inverno,Primavera,Verão,Outono,', 'Manhã', '10,11,12,'),
	(80, 'Pirapema', 'Peixe de couro, corpo alongado e barbilhas longas', 'Peixe pequeno ou carne', 'Isca natural, peixes menores ou carne', 'Rios de grande porte', 5, 15, 'Pesca de fundo', 'https://www.fishtv.com/uploads/noticias/facebook/1200x630/face-5.jpg', 10, 50, 100, 200, 'Inverno,', 'Noite,', '6/0,7/0,8/0,9/0,10/0,11/0,12/0,'),
	(81, 'Camurupim', 'Peixe de escamas, corpo longo e prateado, com boca larga', 'Sardinha ou peixes menores', 'Isca natural, sardinha viva ou peixes menores', 'Estuários e costa marítima', 1, 10, 'Pesca de arremesso ou corrico', 'https://www.fishtv.com/uploads/noticias/interna/2772/3392x2266/b-3.jpeg', 20, 50, 100, 200, 'Verão,', 'Tarde,', '5/0,6/0,7/0,8/0,9/0,10/0,'),
	(82, 'Barbado', 'Peixe de couro, corpo robusto e barbilhas longas', 'Minhoca, peixes pequenos', 'Isca natural, minhoca ou peixes menores', 'Rios e lagos', 2, 6, 'Pesca de fundo', 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuoHNLdeRt4cW1jcRFlKLkKI4A4vWFeW-4hv18VxRAWEbXd5AGkAzp4xTXKA7JM505WjQ&usqp=CAU', 2, 8, 40, 80, 'Inverno,', 'Noite,', '4/0,5/0,6/0,');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
